version: 0.2

env:
  variables:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    FL_OUTPUT_DIR: "output"
    working_directory: "/Users/*********/project"
    shell: "/bin/bash --login -o pipefail"
    SCAN_DEVICE: "iPhone 15 (17.5)"

phases:
  pre_build:
    commands:
        - echo "Listing project information..."
        - xcodebuild -project MyApp.xcodeproj -list
        - echo "Searching for target IDs..."
        - cat MyApp.xcodeproj/project.pbxproj | grep -A 5 "BuildableIdentifier"
        - echo "Current directory contents:"
        - ls -la
        - echo "XcodeProj contents:"
        - ls -la MyApp.xcodeproj
        # ... rest of your pre_build commands

  build:
    commands:
      - echo "checking DerivedData in build"
      - sudo ls -r DerivedData
      - echo "Derived Data points to:"
      - readlink DerivedData
      - echo "Does target exist?"
      - ls -lsa "$(readlink DerivedData)"
      - echo "Run Integration Tests"
      - sudo bundle exec fastlane ios test
      - exit 0
